package com.js.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Code implements Serializable {
    private Long id;

    private String areacode;

    private Integer code;

    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table code
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.id
     *
     * @return the value of code.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.id
     *
     * @param id the value for code.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.areacode
     *
     * @return the value of code.areacode
     *
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.areacode
     *
     * @param areacode the value for code.areacode
     *
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code
     *
     * @return the value of code.code
     *
     * @mbggenerated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code
     *
     * @param code the value for code.code
     *
     * @mbggenerated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.date
     *
     * @return the value of code.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.date
     *
     * @param date the value for code.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}