package com.js.dao.model;

import java.io.Serializable;
import java.util.Date;

public class GenScheme implements Serializable {
    private String id;

    private String name;

    private String category;

    private String packageName;

    private String moduleName;

    private String subModuleName;

    private String functionName;

    private String functionNameSimple;

    private String functionAuthor;

    private String genTableId;

    private String createBy;

    private Date createDate;

    private String updateBy;

    private Date updateDate;

    private String remarks;

    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.id
     *
     * @return the value of gen_scheme.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.id
     *
     * @param id the value for gen_scheme.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.name
     *
     * @return the value of gen_scheme.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.name
     *
     * @param name the value for gen_scheme.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.category
     *
     * @return the value of gen_scheme.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.category
     *
     * @param category the value for gen_scheme.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.package_name
     *
     * @return the value of gen_scheme.package_name
     *
     * @mbggenerated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.package_name
     *
     * @param packageName the value for gen_scheme.package_name
     *
     * @mbggenerated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.module_name
     *
     * @return the value of gen_scheme.module_name
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.module_name
     *
     * @param moduleName the value for gen_scheme.module_name
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.sub_module_name
     *
     * @return the value of gen_scheme.sub_module_name
     *
     * @mbggenerated
     */
    public String getSubModuleName() {
        return subModuleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.sub_module_name
     *
     * @param subModuleName the value for gen_scheme.sub_module_name
     *
     * @mbggenerated
     */
    public void setSubModuleName(String subModuleName) {
        this.subModuleName = subModuleName == null ? null : subModuleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.function_name
     *
     * @return the value of gen_scheme.function_name
     *
     * @mbggenerated
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.function_name
     *
     * @param functionName the value for gen_scheme.function_name
     *
     * @mbggenerated
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName == null ? null : functionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.function_name_simple
     *
     * @return the value of gen_scheme.function_name_simple
     *
     * @mbggenerated
     */
    public String getFunctionNameSimple() {
        return functionNameSimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.function_name_simple
     *
     * @param functionNameSimple the value for gen_scheme.function_name_simple
     *
     * @mbggenerated
     */
    public void setFunctionNameSimple(String functionNameSimple) {
        this.functionNameSimple = functionNameSimple == null ? null : functionNameSimple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.function_author
     *
     * @return the value of gen_scheme.function_author
     *
     * @mbggenerated
     */
    public String getFunctionAuthor() {
        return functionAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.function_author
     *
     * @param functionAuthor the value for gen_scheme.function_author
     *
     * @mbggenerated
     */
    public void setFunctionAuthor(String functionAuthor) {
        this.functionAuthor = functionAuthor == null ? null : functionAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.gen_table_id
     *
     * @return the value of gen_scheme.gen_table_id
     *
     * @mbggenerated
     */
    public String getGenTableId() {
        return genTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.gen_table_id
     *
     * @param genTableId the value for gen_scheme.gen_table_id
     *
     * @mbggenerated
     */
    public void setGenTableId(String genTableId) {
        this.genTableId = genTableId == null ? null : genTableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.create_by
     *
     * @return the value of gen_scheme.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.create_by
     *
     * @param createBy the value for gen_scheme.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.create_date
     *
     * @return the value of gen_scheme.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.create_date
     *
     * @param createDate the value for gen_scheme.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.update_by
     *
     * @return the value of gen_scheme.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.update_by
     *
     * @param updateBy the value for gen_scheme.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.update_date
     *
     * @return the value of gen_scheme.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.update_date
     *
     * @param updateDate the value for gen_scheme.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.remarks
     *
     * @return the value of gen_scheme.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.remarks
     *
     * @param remarks the value for gen_scheme.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_scheme.del_flag
     *
     * @return the value of gen_scheme.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_scheme.del_flag
     *
     * @param delFlag the value for gen_scheme.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}