package com.js.dao.mapper;

import com.js.dao.model.GenScheme;
import com.js.dao.model.GenSchemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GenSchemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int countByExample(GenSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int deleteByExample(GenSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int insert(GenScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int insertSelective(GenScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    List<GenScheme> selectByExample(GenSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    GenScheme selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GenScheme record, @Param("example") GenSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GenScheme record, @Param("example") GenSchemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GenScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_scheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GenScheme record);
}